{{- if .Values.ingress.enabled -}}
{{- $name := include "basic-service.name" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ template "basic-service.name" . }}
    chart: {{ template "basic-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
    {{- range .hosts }}
        - "{{ . }}"
    {{- end }}
      secretName: {{ .secretName }}
  {{- end -}}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
    {{- if $ingressPath }}
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  name: http
    {{- else -}}
      {{- range $ingressPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service
                name: {{ $name }}
                port:
                  name: http
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end }}
