{{- if .Values.persistence.enabled }}
  {{- $root := . }}
  {{- range $index, $volume := .Values.persistence.volumes }}
    {{- if gt $index 0 }}
---
    {{- end }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "basic-service.name" $root }}-pv-{{ $volume.nameSuffix | default $index }}
spec:
  capacity:
    storage: {{ $volume.storage | default "1Gi" }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ $volume.hostPath }}
  storageClassName: pv-{{ $volume.nameSuffix | default $index }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "basic-service.name" $root }}-pvc-{{ $volume.nameSuffix | default $index }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pv-{{ $volume.nameSuffix | default $index }}
  resources:
    requests:
      storage: {{ $volume.storage | default "1Gi" }}
  {{- end }}
{{- end -}}
