kind: Secret
apiVersion: v1
metadata:
  name: {{ template "basic-service.name" . }}-secret
data:
{{- if .Values.secret -}}
{{- range $secret := .Values.secret }}
  {{ $secret.name }}: {{ if $secret.fromFile -}}
    {{- .Files.Get $secret.fromFile | b64enc }}
  {{- else -}}
    {{/* Use printf so that it is always a string */}}
    {{- printf "%s" $secret.value | default "" | b64enc }}
  {{- end -}}
{{- end -}}
{{- end -}}
