# Default values for basic-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The service name, should be overridden by user
# name: basic-service

replicaCount: 1

image:
  # repository: ost.ai/basic-service
  # tag: 1.2.1

  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

container:
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  # Kubernetes does not support gRPC health checks
  # https://github.com/kubernetes/kubernetes/issues/21493
  # so ues tcp for now
  tcp: true
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  tcp: true
  initialDelaySeconds: 15
  periodSeconds: 20

# env:
#   - name: SERVICE_PORT
#     # value will output a simple value
#     value: "80"
#   - name: MYSQL_PASSWORD
#     # will reference the env value to the specific secret key
#     secretKey: MYSQL_PASSWORD
#   - name: MYSQL_HOST
#     configMapKey: MYSQL_HOST

# secret:
#   - name: MYSQL_PASSWORD
#     value: 123456
#   - name: WECHAT_PAY_CERT
#     # this will load secret from file
#     fromFile: /var/run/secrets/ost.ai/wechat_pay.p12

# configmap:
#   - name: CONFIG_NAME
#     value: 123
