{{- if .Values.services -}}
  {{- range $i, $service := .Values.services -}}
    {{- if gt $i 0 }}

---
    {{- end }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $service.name }}
spec:
  ports:
  - protocol: {{ $service.protocol | default "TCP" }}
    port: {{ $service.port }}
    targetPort: {{ $service.port }}

---

kind: Endpoints
apiVersion: v1
metadata:
  name: {{ $service.name }}
subsets:
  - addresses:
      - ip: {{ $service.ip }}
    ports:
      - port: {{ $service.port }}
  {{- end -}}
{{- end -}}
