{{- if .Values.services -}}
  {{- range $i, $service := .Values.services -}}
    {{- if gt $i 0 }}

---
    {{- end }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $service.name }}
spec:
{{- if $service.externalName }}
  type: ExternalName
  externalName: {{ $service.externalName }}
{{- else }}
  ports:
  - protocol: {{ $service.protocol | default "TCP" }}
    port: {{ $service.port }}
    targetPort: {{ or $service.targetPort $service.port }}
{{- end }}
{{- if not $service.externalName }}
---

kind: Endpoints
apiVersion: v1
metadata:
  name: {{ $service.name }}
subsets:
  - addresses:
      - ip: {{ $service.ip }}
    ports:
      - port: {{ or $service.targetPort $service.port }}
{{- end -}}
  {{- end -}}
{{- end -}}
