apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "grpc-service.fullname" . }}
  labels:
    app: {{ template "grpc-service.name" . }}
    chart: {{ template "grpc-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "grpc-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "grpc-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- $root := . -}}
{{- if .Values.env }}
          env:
  {{- range $env := .Values.env -}}
    {{- if $env.secret }}
            - name: {{ $env.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "grpc-service.name" $root }}-secret
                  key: {{ $env.secret }}
    {{- else if $env.config }}
            - name: {{ $env.config }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "grpc-service.name" $root }}-configmap
                  key: {{ $env.config }}
    {{- else }}
            - name: {{ $env.name }}
      {{- if $env.configMapKey }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "grpc-service.name" $root }}-configmap
                  key: {{ $env.configMapKey }}
      {{- else if $env.secretKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "grpc-service.name" $root }}-secret
                  key: {{ $env.secretKey }}
      {{- else }}
              value: {{ $env.value }}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
            # Kubernetes does not support gRPC health checks
            # https://github.com/kubernetes/kubernetes/issues/21493
            # so ues tcp for now
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
